version: '3.8'
services:
  # development
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    environment:
      NODE_ENV: development
    env_file:
      - .env.local
    ports:
      - 3000:3000
      - 9229:9229 # for node debug
    command: [ "npm", "run", "dev" ]
  # production
  prod:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    environment:
      NODE_ENV: production
    ports:
      - 80:3000
    command: [ "npm", "start" ]
