name: Build & Deploy

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "app/**.*"
      - "public/**.*"
      - "package.json"
      - "package-lock.json"
      - "next.config.json"
      - "tailwind.config.json"
      - "postcss.config.json"
      - "tsconfig.json"
      - "Dockerfile"
      - ".github/workflows/**.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "18"
  AZURE_WEBAPP_NAME: "ct-azure-openai-gpt4-chat"
  AZURE_WEBAPP_PACKAGE_PATH: "."
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  AZURE_OPENAI_BASE_PATH: ${{ secrets.AZURE_OPENAI_BASE_PATH }}}
  AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
  AZURE_OPENAI_MODEL_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_MODEL_DEPLOYMENT }}
  AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}

jobs:
  build-and-deploy:
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    runs-on: ubuntu-latest
    steps:
      - name: 👷 Checkout Repo
        uses: actions/checkout@v3

      - name: 🏗️ Setup Node.js ${{ env.NODE_VERSION }} environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: ⚡  Cache node_modules
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/node_modules
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-

      - name: ⬆️ Update npm and install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: npm i --location=global npm && npm install

      - name: 🛠️ Build app
        shell: bash
        run: npm run build

      - name: 📦 Zip all files for deployment step
        # IMPORTANT: .next is a hidden folder and will NOT be included in the zip unless we specify it
        run: zip ${{ env.AZURE_WEBAPP_NAME}}.zip ./* .next -qr

      - name: 🚀 Deploy to Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{ env.AZURE_WEBAPP_NAME}}.zip
